name: Build Next.js App

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_PROJECT_API=${{ secrets.PROJECT_API_URL }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # 关键修复
        with:
          name: nextjs-build
          path: .next/
